modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "stackable_elytra_trims"
version = "${version}"
displayName = "Stackable Elytra Trims"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.stackable_elytra_trims]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackable_elytra_trims]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackable_elytra_trims]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stackable_elytra_trims.mixins.json"
