modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "stackable_elytra_trims"
version = "${version}"
displayName = "Stackable Elytra Trims"
authors = "Golem"
description = '''
Allows multiple stacked trims to render on elytras.
'''
#logoFile = "icon.png"

[[dependencies.stackable_elytra_trims]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackable_elytra_trims]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackable_elytra_trims]]
modId = "stackabletrims"
type = "required"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.stackable_elytra_trims]]
modId = "elytratrims"
type = "required"
versionRange = "[4.0,)"
ordering = "AFTER"
side = "CLIENT"

